version: "3"
services:
  reru_db:
    image: mysql:5.7
    ports:
      - "3308:3306"
      - "33080:33060"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: reru_db

  reru_dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=reru_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - reru_db
    ports:
      - 3001:80

  reru_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data: