version: "3"
services:
  reru_db:
    image: mysql:5.7
    ports:
      - "3308:3306"
      - "33080:33060"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: reru_db

  reru_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  reru_rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment: 
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST_NAME: reru_db
      REDIS_URL: redis://redis:6379
    image: rails.dev
    volumes:
      - .:/server:delegated
      - gem_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - reru_db
      - reru_redis
    tty: true
    stdin_open: true

  reru_dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=reru_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - reru_db
    ports:
      - 3001:80



volumes:
  mysql_data:
  gem_data:
