source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'annotate'
gem 'asset_sync'
gem 'aws-sdk-rails'
gem 'aws-sdk-s3', require: false
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'bullet'
gem 'cocoon'
gem 'database_cleaner'
gem 'database_rewinder'
gem 'dotenv-rails'
gem 'draper'
gem 'enumerize'
gem 'faker'
gem 'fog-aws'
gem 'gimei'
gem 'html2slim'
gem 'image_processing', '~> 1.2'
gem 'jbuilder', '~> 2.7'
gem 'kaminari'
gem 'mysql2', '~> 0.5'
gem 'paranoia'
gem 'puma', '~> 5.0'
gem 'pundit'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '~> 6.1.0'
gem 'rails-i18n'
gem 'ransack'
gem 'react-rails'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'redis-rails'
gem 'rotp'
gem 'sass-rails', '>= 6'
gem 'seed-fu'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sidekiq'
gem 'slack-ruby-client'
gem 'slim-rails'
gem 'turbolinks', '~> 5'
gem 'webpacker', '~> 5.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman', require: false
  gem 'factory_bot_rails'
  gem 'packwerk'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec_junit_formatter'
  gem 'rspec-parameterized'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'spring-commands-rspec'
end

group :development do
  gem 'letter_opener_web'
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
  gem 'yard'
  gem 'yard-activesupport-concern'
end
